### ISSUE TITLE
[Feature]: Adding of Executes plugin

### ISSUE THREAD

**Issue by mavproductions** [kus/cs2-modded-server#46]
### Information

Hello!

Please consider adding Executes by B3None and zwolof. ---> https://github.com/zwolof/cs2-executes

Thanks!

**Comment by kus** [comment]
Hey @mavproductions 

I have added the Executes plugin.

To load it, if you are an admin type `!rcon exec executes` in chat or from server console `exec executes`.

At the moment all they support is `de_mirage` so that is the default map loaded. I will keep it up to date with the plugin as they bring out more features or add more maps.

Thanks!
